using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;

namespace excuserandomgenerator
{
    public class excuses
    {   
        public string [] itexcuse = { "Az elfogadási kritériumok teljesülése érdekében tanácsos A/B tesztelni az elosztott utasításokat.",
            "Titkosított kapcsolaton keresztül javasolt beégetni a koherens felhasználói célokat.", "CSS grid, vagy flexbox alkalmazása folytán javallott debuggolni a párhuzamos auto layoutot.",
            "Manapság már alap kibővíteni a valós idejű fordítót.","A megtervezett, kapacitásilag a lehetőségekhez mérten feltöltött projekt megvalósítása érdekében szükséges letesztelni az eseményvezérelt cookie-kat.","Az előzetesen kiválasztott keretrendszert használva érdemes beégetni a valós idejű kompenzációs tranzakciókat."
        ,"A rendszer által kínált hozzáférés-kezelés miatt szükséges kielemezni a költséges bugokat.","A backlog groomingok alkalmával véglegesített sztorik miatt kell debuggolni a számításigényes aktív szerveroldalakat.","Maximális hatékonysággal kell kibővíteni a reszponzív nyelvi fájlokat.",
            "Az offline működés érdekében tanácsos buildelni a számításigényes fejlesztő környezetet.", "A sémafordító segítségével lehet szerializálni az elosztott konstansokat.","A funkcionális specifikáció alapján indokolt újraírni a bináris konstansokat."
        ,"A mobilstratégia miatt elvárt letesztelni a valós idejű konstruktort.","A nagyméretű, robosztus üzleti alkalmazások miatt kell telepíteni az eseményvezérelt konstruktort.","A verziókövetés miatt ajánlott kibővíteni a független osztályokat.",
            "A projekt indító dokumentum szerint kell indexelni az időzített processzeket.","Maximális hatékonysággal kell konfigurálni az eseményvezérelt konstansokat. ","A GPS és egyéb mozgást érzékelő szenzorok maximális kihasználása végett kell konvertálni a base64 kódolású adatbázist. "
                ,"Tárolt eljárások alkalmazásával szükséges buildelni a végtelen üzleti célokat. ","Maximális hatékonysággal kell törölni a nagy rendelkezésre állású reguláris kifejezéseket. ","Titkosított kapcsolaton keresztül javasolt lokalizálni a releváns interfészt. ",
            "Maximális hatékonysággal kell telepíteni a végtelen függvényeket. ","Felhő-alapú fájlmegosztó rendszer használatával kell kódolni a költséges bemeneti és kimeneti értékeket. ","Kiemelt prioritással kell újraírni a hátultesztelős memóriahasználatot. ","A túl sok I/O művelet miatt elengedhetetlen supportálni a flexibilis auto layoutot. ","Az offline működés érdekében tanácsos megtervezni a szerveroldali compilert. "
                ,"A megtervezett architektúra szerint érdemes elkészíteni a platformfüggetlen függvényeket. ","A speciális karakterek numerikus hivatkozássá való kódolásához javasolt supportálni a testreszabott bemeneti és kimeneti értékeket. ","A megtervezett architektúra szerint érdemes supportálni a fix pontosságú dinamikus csatolású függvénykönyvtárakat. "
                ,"Az agilitás jegyében elengedhetetlen meghívni a szinkron működésű auto layoutot. ","A fejlesztői és üzemeltetői teamek hatékony együttműködése érdekében fontos örköltetni az opcionális aktív szerveroldalakat. ","Az előzetesen kiválasztott keretrendszert használva érdemes konvertálni a definiált dinamikus csatolású függvénykönyvtárakat. ","Támogatottsági problémák miatt tanácsos kódolni az eseményvezérelt debuggert. ",
            "Felhő-alapú fájlmegosztó rendszer használatával kell inicializálni a kliensoldali headert. ","A gördülékeny, felhasználóbarát működés miatt kívánatos konfigurálni a valós idejű láncolt listákat. ","A rendszer által kínált hozzáférés-kezelés miatt szükséges leprogramozni a hátultesztelős deadlockot. ","Kiemelt prioritással kell loggolni az alapértelmezett bemeneti és kimeneti értékeket. ","A TDD módszertan alapján indokolt beégetni a decentralizált IDE-t. ",
            "Figyelembe véve a határidőket muszáj lefejleszteni a permanens aktív szerveroldalakat. ","A technical dept kiküszöbölése érdekében szükséges kielemezni a decimális kódbázist. ","A retrospektíven megbeszéltek miatt elkerülhetetlen elkészíteni a jól struktúrált technikai korlátokat. ","A projekt státusz riport szerint megéri indexelni a decimális interfészt. ","Csak alfa tesztelés után lehet újraírni a hátultesztelős aktív szerveroldalakat. ",
            "Csak két iparág dolgozói nevezik felhasználóknak az ügyfeleket: az illegális drogárusok és a szoftverfejlesztők.","A jövő háborúját a számítógépek és a mögöttük ülő programozók vívják. -Kánai András ","Sose bízd emberre egy komputer munkáját.","A számítógép matematikai eszköz, amelyet adatok tárolására és kezelésére hoztak létre. A felelősség azoké az emberi lényeké, akik beprogramozzák és kezelik - s ha olykor mögéje rejtőznek, hogy leplezzék saját alkalmatlanságukat, ez inkább az ember hibája, mint a számítógépé. -Isaac Asimov ","Kinyírnak a vírusok, lefagyott a gépem,megette a kék halál a Windowst egészen. -Horváth Viktor ","Az első ultraintelligens gép az utolsó találmány, amelyet az embernek meg kell alkotnia.-Irving J. Good ","Nincs rosszabb, mint amikor egy eleve rossz folyamatot automatizálnak. -Bill Gates ",
            "A program futtatása az igazi teszt. Megírod a programot, kipróbálod, és vagy működik, vagy nem. -Bill Gates ","Tévedni emberi dolog. A számítógépet hibáztatni még emberibb. -Al Rodrigo ","Hogy minden szellemi tevékenység között a számtani a legalsóbb rendű, annak az a bizonyítéka, hogy ez az egyedüli, amelyet géppel is el lehet végezni. -Arthur Schopenhauer ","Easter Egg: Az alkalmazást Korek György készítette Xamarin.Android alapokon.","A 90-es években a Microsoft a saját Java keretkörnyezetét a saját operációsrendszer-specifikus függvényeivel és szolgáltatásaival bővítette ki."
                ,"A C# fejlesztését Anders Hejlsberg vezette, aki a Turbo Pascal tervezője is volt. A .NET osztálykönyvtárait a programozók eredetileg egy sajátos, ún. SMC (Simple Managed C) nyelven írták. " ,
            "Tulajdonságok (Properties) használhatók, amelyek úgy tesznek lehetővé kódfuttatást mezők beállításakor és olvasásakor, hogy közben az adattagok szintaxisát használja. " ,"A metódusok a Javában alapból virtuálisak, ellentétben a C#-pal " ,"A C# esetén van unchecked (nem ellenőrzött) kontextus, amiben a változók túlcsordulása és helyes típus konvertálása felülbírálható (optimalizációt segíti) "};
        public string[] hrexcuse = { "Az emberi erőforrás (Human resource management, HRM vagy HR ) gazdálkodásának megértéséhez a vállalati erőforrások rendszeréből kell kiindulni. ", "A legalkalmasabb emberek megtalálása szervezeten belül vagy kívül, belső erőforrások átcsoportosítása (ez mindkét fél számára előnyös, mert ezzel a munkavállaló számára előrelépést jelent, a munkáltató számára nem okoz meglepetést a munkavállaló) Külső keresés esetén megfelelő módszerekre van szükség a jelöltek érdekében: tesztekre, interjúkra.",
        "Bérezésének alapja az elért eredmények szisztematikus felmérése és értékelése. ", " Vizsgálja a hiányosságokat, a jövő időszak követelményeit, a szükséges képzési és fejlesztési igényeket." , "Információt nyújthat a szervezet jövőbeli teljesítőképességének megítéléséhez is. Meghatározza, felülvizsgálja a munkakörhöz kapcsolódó ösztönzőket, ezek hatását a magatartás változására az alkalmazott elégedettségére (elismerések, jutalmak, díjak).",
        "Külső vagy belső képzéssel és tréninggel lehetséges. A képzési szükségleteket a teljesítményértékelés és/vagy a karriertervezés alapján határozzuk meg. A karriertervezés az egyén szervezeten belüli mobilitásnak előrejelzése.", " Az ösztönző rendszer az alkalmazott szempontból alapvető fontosságú ellenszolgáltatások összessége.", " Alapjául a munkaköri követelmények, a munka tartalma vagy a munkaerő-piaci keresleti kínálati viszonyok szolgáltatnak.",
        "Azonos munkakörök járhatnak különböző jutalmazással pl. szolgálati idő vagy a befolyásoló hatása következtében.", "A bér és a fizetés mellett a javadalmazásnak még számos más formája van pl. pótlólagos szabadság, életbiztosítás, megtakarítási alapok, nyereségarányos jutalom.", "Egydimenziós szervezetek: csak az egyik munkamegosztási elv érvényesül."
        ,"Alapvető munkamegosztásból tagoltság két formája együtt jelenik meg (pl. funkció és termék). ","Előnye, hogy a két vezető egy kérdésben dönthet, ezért szélesebb horizonton, ez innovatív szemlélet.","A menedzserek közti interakciók javíthatják a szervezet irányításának a minőségét. ","A konfliktusok megoldásának pozitív hatása építő, előremutató a cég számára, állandó tanulási folyamat. Hátránya, hogy a menedzserek közti rivalizálás hatalmi harcot hozhat létre. ","A munkáltatói márkaépítés (angolul employer branding) az a folyamat, ahol az értékek tudatosítása, kommunikációba ültetése és működtetése, a hiányzó, de szükséges értékek kialakítása, valamint a hiányos értékek fejlesztése történik."
        ,"Annak érdekében, hogy a munkáltató (a cég) megfelelő minőségű munkaerőhöz jusson, a munkaerő-piacon vonzó képet kell kialakítania magáról.","Objektív módszerekkel kell a munkát betanítani. Folyamatosan ellenőrizni kell. Külön kell kiválasztani a vezetőt és a munkást. Mindenki a saját feladatával foglalkozzon (fehér és kék gallérosok). Szerinte a munkás a gép tartozéka. -Taylor","Természetesen a szervezet belső folyamatai, a szervezeten belüli szabályozás, a szervezeti stratégia, a cégen belüli érdekképviseletek, szakszervezetek befolyásolják az EE működését.","A makrogazdaság általános folyamatai, a munkaerő-piaci viszonyok (hat az ösztönzésre), a jogi szabályozás, üzleti környezet, a kulturális hagyományok, a munkavállalói szervezetek."," Az emberi erőforrás tervezés: minőségi és mennyiségi szükségletek előrejelzése, valamint tevékenység-meghatározás."
        ,"Ez a kép a munkáltatói márka (angolul employer brand), amely nem más, mint a vállalat közös értékeinek tudatos működése a vállalat külső, belső kommunikációjában.","A munkavégzés módját pontosan meg kell határozni.","A márka egy név, kifejezés, jel, szimbólum, dizájn vagy ezek kombinációja. A márka feladata, hogy egy eladó vagy egy termék/szolgáltatás megkülönböztethető legyen a piacon elérhető versenytársaktól.","Egy jó márka alkalmas a termék/eladó azonosítására és megkülönböztetésére. ","Egy vállalatnak akkor is van márkája, ha nem követ tudatos márkaépítés stratégiát: minden amit a vásárlók, alkalmazottak, beszállítók és partnerek gondolnak a cégről, részét képezi a márkának."
                , "A piacgazdaságban (market economy) az egyének és a magántulajdonban levő vállalatok hozzák meg a termelést és a fogyasztást érintő döntéseket. A leggyakoribb tulajdonforma a magántulajdon. ", "A vegyes gazdaság olyan gazdaság, amelyben vegyes koordináció valósul meg. Itt az állami és magánszféra is részt vesz a termelésben. A piaci verseny dominál, azonban kormányzati közreműködéssel. ",
            "A vegyes, vagy piacgazdaságot általában „nyomásos” piac jellemzi.", "A tőzsdei ügylet az a szerződés, amelyet a tőzsdei kereskedési joggal rendelkezők a tőzsdén forgalmazott árukra vonatkozóan egymással kötnek. ", " A tisztán piac alapú gazdaságok jellemzője az, hogy a monetáris politika elsődleges célja az árstabilitás, míg a vegyes gazdaságokra jellemző a foglalkoztatás magas szinten való tartása."
        , "A valódi marketing nem egyenlő az eladás művészetével, annál sokkal több, a szükséges cselekedetek tudásának művészete.", "Fogyasztási cikkek esetén a marketingkommunikációs üzenetek, azaz a reklámok tehát alapvetően (de nem feltétlenül) a vállalatok irányából érkeznek és alapvetően (de nem feltétlenül) a fogyasztók felé irányulnak. "
        , "A marketingtudomány termékekre vonatkozó műveletei legtöbbször a szolgáltatásokra is érvényesek, utóbbiak azonban néhány olyan különleges tulajdonsággal is rendelkeznek, amelyeket a termékekre fókuszáló marketing nem tud kezelni. ", "Kutatható tulajdonságok: a szolgáltatás azon jellemzői, amelyeket igénybevétel előtt meg tudunk vizsgálni, képesek vagyunk értékelni."
        , "A marketingmixben megismert eszközök mind olyan eszközök, amelyekre a szervezet közvetlenül tud hatni. A vállalatok marketingtevékenységét azonban számos olyan külső tényező befolyásolja, amelyekre a vállalatoknak elenyésző vagy egyáltalán nincs ráhatása. ", "Ebből kifolyólag a szolgáltatások esetén többféle tulajdonságról beszélhetünk."
        , "Egyidejűség (inseparability): a legtöbb esetben a szolgáltatások előállítása, megvásárlása és igénybevétele ugyanabban az időben történik.", "Tárolhatatlanság (perishability): a szolgáltatások nem raktározhatóak vagy készletezhetőek, így nem vehetjük őket igénybe egy másik időpontban."
        , "A marketingkommunikációs politika tehát magába foglalja a marketingkommunikációs aktivitások megtervezését és kivitelezését, illetve a reklámhatás mérését és elemzését.", "Vond magadra a figyelmet, tartsd fenn az érdeklődést, kelts vágyat, és válts ki cselekvést!"
        , "Márkaértéken a márkának azon tulajdonságait értjük, melyek révén az egyes termékek és szolgáltatások fogyasztóinak valamilyen többletet képes nyújtani", "B2C (business to consumer, azaz a vállalatoktól a fogyasztók felé irányuló) marketing a fogyasztási cikkekre fókuszál."};
        public string[] kesesexcuse = {"Egy elszabadult zebra akadályozta a forgalmat az autópályán, amíg el nem fogták.",
        "A reggel két háztömbnyire a lakásomtól, a szomszéd füvén ébredtem.",
        "Házikedvencünk beleszorult a wc-be és őt kellett kiszabadítanunk.",
        "Nem volt otthon tej a reggeli müzlihez, így muszáj volt boltba mennem.",
        "Azért késtem, mert a fáradságtól elaludtam az autóban munkába menet.",
        "Kontaktlencse-folyadék helyett ragasztót cseppentettem a szemembe, így munka helyett a sürgősségire kellett mennem.",
        "Ma nem munkaszüneti nap van?",
        "A hálószobaplafon beázott, a víz éppen az ébresztőórára csöpögött, ami ettől tönkrement, és nem működött reggel.",
        "A reggeli TV műsor végét mindenképp meg akartam várni.",
        "Elfelejtettem a címet.",
        "Belegubancoltam a fésűt a hajamba, és nem tudtam kiszedni.",
        "Éjszaka rosszat álmodtam, és féltem bemenni dolgozni.","Nem engedte a postás hogy kimenjek a kapun.","Nem találtam otthon maszkot.","Társadalmi felelősségvállalásom jegyében úgy éreztem érdemes elkerülnöm a reggeli tömeget.",
        "Rossz időzónára állította át magát a telefonom. "};
        public string[] deadlineexcuse = { "Hogy micsoda? Nem, nem kaptam tőled ilyen emailt, biztos valami gond lehetett a levelező rendszerrel."
                ,"Sajnos véletlenül kitöröltem az email-edet, ezért nem tudtam a feladatról ", "Biztos, hogy elküldted a levelet? Szerintem csak akartad, menj, nézd meg, tuti ott van a piszkozatok között! ", "Napi 200 emailt kapok, sajnos nem tudok mindig mindent elolvasni, így erről a feladatról nem tudtam. ", "Küldtél emailt? Tudhatnád, hogy azokat sosem olvasom. Ha valami fontos, hívj fel máskor! De azért írj róla emailt is, hogy legyen nyoma! Legjobb, ha SMS-t is írsz meg Messenger üzit, akkor valószínűbb, hogy meglesz. ", "Nem készültem el, mert el voltam havazva. "
        ,"Három projektben is benne vagyok, mindegyik kritikus fázisban van, ezek miatt teljesen el vagyok havazva, nem készültem el. ","Tudhatnád, hogy mind a három másik projektem kritikus fázisban van, nélkülözhetetlen vagyok bennük, kiújult az isiászom, allergiás a kutyám, az igazgatótanács naponta státuszoltat minket, nyakunkon a globális felmelegedés, nem hiszem el, hogy még te is b@sztatsz ezzel az idegesítő kis hülyeséggel! ","Sajnos nem volt elég részletes a specifikáció, ezért vannak kritikus hibák a projektben. ","Nem tudom, nálam működik. "
        ,"Ez nem hiba, ez feature. ","Nagyon hosszú volt a specifikáció, arra a részre sajnos nem emlékeztem. ","Ezt a specifikációt elolvasták még hatan rajtam kívül, ők miért nem vették észre benne a hibát?? ","BIZTOS, hogy abban, amit én olvastam, nem így volt benne. Az a szemét szállító utólag átírta a specifikációt!  ","Sajnos elhúzódott az előző meetingem, azért  nem tudtam bfejezni a projektet. "
        ,"Óriási dráma van, de top szikret, nem beszélhetek róla, tudjuk le ezt az izét tíz perc alatt, aztán rohanok tovább. ","De kurv@ra ráértek, hogy van időtök itt üldögélni, és engem várni! ","Sajnos nem tudtam, hogy ez az én feladatom. ","Ez nem hozzám tartozik. ","A csúszás oka az, hogy késtünk a modulok tesztelésével. "
        ,"A csúszás oka az, hogy a szállító késett a modulok tesztre adásával. ","A kutyád megette a prezentációmat. ","Ez ellentétes az irányelveinkkel. ","Már az elején láttam, hogy tarthatatlan lesz a határidő, de nem akartam szólni. ","Pedig tegnap megcsináltam, hová tűnt? "
        ,"Kell még egy kis idő, hogy befejezhessem tökéletesen. ","Nem éreztem tökéletesnek, ezért az elejéről kezdtem a munkát tegnap. "};
        public string[] trainingexcuse = {"Holnap sokkal több kedvem lesz hozzá, kedv nélkül nem lehet.","Már késő van, holnapi napomat jobban megtervezem majd.","Túl korán van hozzá, rengeteg dolgom van még a napra"
        ,"Majd megyek edzeni, ha nem esik az eső. ","Majd ha nincs ekkora hó. ","Majd ha nem lesz ekkora hőség. ","Nem edzek, mert féltem a derekamat/térdemet. ","Fáj a fejem. ","Fáradt vagyok, egész nap dolgoztam. ","Már egy hónapja nem fejlődtem semmit, nincs értelme edzeni. "
        ,"Nincs rá időm.", "Nincs rá időm. ", "Ezt még be kell fejeznem mára. ", "Túl izmos leszek ha edzek. ", "Most nem tudok lemenni, épp játszok. ","A párommal kell foglalkoznom. ","A régi sportsérülésem miatt kímélnem kell magam!","És a párom addig mit kezd magával, amíg én edzek?!","Nem tudok eleget edzeni, akkor meg egyszer egy héten minek menjek?"
                ,"Egyszerűen nincs kedvem edzeni!", "Nincs pénzem rá most. ", "Unalmas nekem az edzés ma. ", "Beteg / sérült vagyok, majd ha jobban leszek. ", "Nem vagyok sportoló – mit mozogjak egyáltalán? ", "Az edzés olyan, mint a házimunka és nincs kedvem hozzá. "
        , "Megvárom a következő hónapot/hetet. ", "Előbb lefogyok mielőtt elkezdenék komolyan edzeni. ", "Most mostam hajat. ", "Majd megyek holnap. "
        , "Munkahelyi kötelezettségeim vannak. ", "Nem borotváltam. (Ez jobb esetben csak női kifogás) ", "Már edzettem ma, sétáltam sokat. ", "Nem ettem eleget ma. "
        , "Odajárnak a kollégáim, ismerőseim akiket rühellek. ", "Nem engedhetem meg anyagilag magamnak, hogy drága fitnesz felszereléseket vásároljak, vagy, hogy eljárjak edzésre, majd később. ", "Ma megsérülnék úgyérzem. "};
        public string[] todayexcuse = { "Holnap több lesz a kedvem hozzá.","Ma már nincs rá elég időm." };
        public string[] sleepoverexcuse = {"Nem aludhatok nálad, reggel korán kell gumicserére vinnem az autót.", "Szüleimnek megígértem, hogy korán megyek segíteni. ", "Reggel szerelőhöz kell vinnem a kocsit. ", "Időpontom van valahova holnap az ország másik felében. ", "Nem érzem valami jól magam. "
        ,"Rengeteg munkám van a hétre.","Holnap vizsgázok.", "Holnap prezentálom a projektemet, át kell néznem még az este.","Nincs nálam a kontaklencsetartóm és folyadékom.","Reggel megyek kontrollra.","Fáj a hasam.","Fáj a fejem."};
        public string[] lawexcuse = { "A más néven dogmatikus, vagy tett- büntetőjogi iskola előfutára Cesare Beccaria volt.","Ez az alapelv a biztosítéka annak, hogy az elkövetőt is megillessék mindazok a jogok, amelyeket az adott állam magasabb rendű szabályozása, s nemzetközi jog emberi jogokként elismernek.  ", "Tartalmazza azt, hogy csakis a bűnösen tanúsított magatartásért legyen felelősségre vonható az elkövető. Az elven belül két dogmatikai felfogás mutatható ki. ", "A Kúria (korábbi nevén Legfelsőbb Bíróság) Büntető Kollégiumának állásfoglalásai, bár nem bírnak ugyan jogforrási erővel, de hatásuk az igazságszolgáltatásra tagadhatatlan.  ", "A szokásjog jogforrási erejét modern államok büntetőjogában semmiképpen sem ismerhetjük el (történelmileg jelentős hatása volt). Érdekes problémát vetnek fel a keretjogszabályok: a nullum crimen elvének megfelelően csakis az lehet bűncselekmény, amit törvény annak minősít. "
        , "Időbeli hatály: a bűncselekményt az elkövetése idején hatályban lévő büntető törvény szerint kell elbírálni. Ha a cselekmény elbírálásakor hatályban lévő új büntető törvény szerint a cselekmény már nem bűncselekmény, vagy enyhébben bírálandó el, akkor az új büntető törvényt kell alkalmazni.  ", "Területi és személyi hatály: a magyar büntető törvényt kell alkalmazni a belföldön elkövetett bűncselekményre, a Magyarország területén kívül tartózkodó magyar felségjelű úszólétesítményen vagy magyar felségjelű légi járművön elkövetett bűncselekményre, illetve a magyar állampolgár által külföldön elkövetett olyan cselekményre, amely a magyar törvény szerint bűncselekmény. ", "A jogszabály értelmezésének célja a jogszabályban megnyilvánuló törvényhozói akarat pontos tartalmának a megállapítása, ami a büntető jogszabályok helyes alkalmazásának alapvető feltétele. ", "Bűncselekmény az a szándékosan vagy - ha a törvény a gondatlan elkövetést is bünteti - gondatlanságból elkövetett cselekmény, amely veszélyes a társadalomra, és amelyre a törvény büntetés kiszabását rendeli. A bűncselekmény bűntett vagy vétség.  "
        , "A szubszidiaritás azt a követelményt fejezi ki, hogy a büntetőjog alapvetően ultima ratio legyen, az alkalmazására csak akkor kerüljön sor, szubszidiárius (kisegítő) jelleggel, ha más jogágban található eszközökkel a büntetőjog által védett életviszonyok védelme nem megoldható.  ", "Az analógia problémáját az a helyzet veti fel, mikor a törvényhozó két hasonló életviszony közül az egyiket szabályozta, míg a másikat szabályozás nélkül hagyta, és a jogalkalmazó a nem szabályozott életviszonyra – a hasonlóság okán – a másik, szabályozott életviszonyra vonatkozó szabályozást alkalmazza. ", "Alkotmány alatt általában a társadalom működésével kapcsolatos érdekek és célok, az állam belső szabályozására és külkapcsolatára vonatkozó alapelvek, a jogforrási rangsor csúcsán elhelyezkedő, egy alaptörvényben megjelenő összességét értjük. ", "A római jog a Római Birodalomnak a köztársaság koráig visszavezethető jogrendszere. Eredete a XII táblás törvényekig nyomonkövethető.  "
        , "A római jog a Római Birodalomnak a köztársaság koráig visszavezethető jogrendszere. Eredete a XII táblás törvényekig nyomonkövethető. ", "A Pandekták dogmatikai szempontból tárgyalják a Corpus Iuris tartalmán alapuló s ezen az alapon rendszeresen kidolgozott általános magánjogtant.  ", "A római jog Európa-szerte gyűjtött tapasztalatok szerint a legajánlatosabb tanjog. Kipróbált képző eszköze a jogi oktatásnak. Ezért fordul elő a világon minden egyetemi tanrendben.  ", "Justinianus négy műve egységbe foglalva (Corpus Iuris Civilis) záróköve a régi, de egyszersmind kiindulási pontja a későbbi jogfejlődésnek. Középponti helyzeténél fogva két tantárgy épül rá: az Institutiók és a Pandekták.  "
        , "Ha Németországban, a német polgári törvénykönyv életbe léptetése következtében elveszti is külső alaki érvényességét s épp ezért a porosz igazságügyi miniszter 1886. évi rendeletével a német polgári jog előadását helyezi a tanfolyam első felébe: a római jognak belső értéke független marad a külső kötelező erőtől.  ", "A római jog hazánkba úgy érkezett, mint a latin nyelv. A kereszténység egyengette az utat a civiljog számára. Amikor a bolognai egyetem, Könyves Kálmán királyunk óta, a római jogot terjesztette, hazánk sem zárkózhatott el az új irány előtt.  ", "Az 1997. évi CXLI. törvény szerint ingatlan az olyan földrészlet, amely az ingatlan-nyilvántartásba önállóan bejegyezhető. ", "Lakóingatlan lyan épület, mely használatbavételi vagy fennmaradási engedéllyel rendelkezik, telekkönyvi szempontból befejezettnek minősül és a használatba vételi engedély telekkönyvileg be van jegyezve. "};
        public string[] engineeringexcuse = { "A hidrodinamika alapján a folyadék mozgását a Lagrange- vagy Euler-módszer szerint írják le. A hidrodinamika alapegyenletei az Euler-féle mozgásegyenletek; viszkózus folyadékokra is érvényes változataik a Navier—Stokes-egyenletek.", "A kvantummechanika a fizika azon ága, amelyik a nanoszkopikus méreteknél történő jelenségeket vizsgálja; így az elemi részecskék viselkedését vagy például az olyan alacsony hőmérsékletű makrojelenségeket, mint a szuperfolyékonyság és a szupravezetés.  ", "A hullámfüggvény az időben fejlődhet. Például az üres térben mozgó részecske ábrázolható egy átlagos helyzet körül el nem tűnő hullámcsomaggal.  "
        , "Mint a bevezetés is említi, több olyan jelenség van a kvantummechanikában, aminek nincs klasszikus megfelelője. Ezeket gyakran kvantumeffektusoknak hívjuk. ", "	Szabad – azaz kölcsönhatásmentes – tömegpontokat síkhullámmal írhatunk le:ahol ω a hullám körfrekvenciája, k pedig a hullámvektora. Következő lépésként behelyettesítettük a hullám-részecske kettősség összefüggéseit, amik a részecske E energiáját és p impulzusát kapcsolják össze a hullámot leíró mennyiségekkel. ", "Az EPR-paradoxon (Einstein–Podolsky–Rosen-paradoxon) a kvantummechanika egyik nevezetes gondolatkísérlete, amelynek eredeti célja az elmélet nem-teljes voltának demonstrálása volt, később pedig a kísérleti ellenőrzésében játszott szerepet. ", "A Heisenberg-féle határozatlansági reláció szerint egy részecske spinje két, egymásra merőleges irányban egyszerre nem mérhető meg. "
        , "Az EPR-paradoxon Bohm által adott (EPRB-paradoxonnak is nevezett) megfogalmazásában egy forrás két elektront bocsát ki, amelyek együttes spinje nulla, és mindkettő a pozitív és a negatív spin kvantum-szuperpozíciójában van (azaz a két részecske összefonódott állapotban van). "
        , "A paradoxont Albert Einstein, Boris Podolsky és Nathan Rosen publikálta 1935-ben. ", "A kvantum-szuperpozíció a kvantummechanikai rendszerek azon állapota, mikor egyidejűleg két (vagy több) helyzetben is (például van-nincs állapotban) létezhetnek egyszerre. ", "A Schrödinger macskája Erwin Schrödinger Nobel-díjas osztrák fizikus nevéhez fűződő gondolatkísérlet. A tudós ezzel a kísérlettel kívánta szemléltetni a mikrovilágban uralkodó törvények hétköznapi szemlélet számára meghökkentő idegenszerűségét, azt, hogy a részecskék egyidejűleg több helyen, különféle állapotokban lehetnek. ", "A kvantummechanikában szuperpozíciónak nevezik, amikor egy elemi részecske (vagy részecskékből álló rendszer) ún. kevert állapotban van, azaz bizonyos tulajdonságait nem tudjuk egyértelműen.  "
        , "A coloradói Boulderben lévő Műszaki és Szabványügyi Intézet (NIST) kutatói 1996-ban sikeres kísérleteket folytattak a kvantum-szuperpozíció összeroppanásának vizsgálatára. ", "A húrelmélet és az M-elmélet két egymásra épülő részecskefizikai modell, mely a részecskéket nem pontszerű, hanem kiterjedt objektumokként kezeli (húrok, membránok). A húrelméletnek a szuperszimmetriát is tartalmazó változatát gyakran szuperhúrelméletnek nevezik. ", "A húrelméletnek három komolyabb problémája van. Az első, hogy senki sem képes megoldani a húrok mezőelméletét, vagy hogy bármilyen más nemperturbatív eredményt hozzon ki a húrelméletből. A feladat kristálytiszta, de a sors iróniája, hogy a megoldása olyan technikákat igényel, amelyek túlmutatnak a fizikusok jelenlegi képességein.  ", "Öt különböző típusú húrelmélet létezik. Ezek a következőek: I típus, IIA típus, IIB típus, heterotikus-O és heterotikus-E. Ezekről sokáig azt hitték, hogy különbözőek, de a közelmúltban kiderült, hogy a húrelméletek között van összefüggés.  "};
        public string[] artexcuse = { "Az egyik lehetséges felosztás szerint a művészeteket művészeti ágazatok alkotják, ilyen például a zene, a tánc, a képzőművészet, az iparművészet, az építészet, az irodalom stb. Egy-egy ágazatot pedig művészeti ágak együttese alkotja. Így például a képzőművészeten belül a szobrászat, a grafika, a fotó, festészet.", "Az ókori rómaiak a temetési szertartásokon őseik viaszképmását hordozták a gyászmenet előtt, nyilván ők is azt hitték, hogy a képmásban a halott lelke él tovább. "
        , "A római festészet maradványai leginkább Pompeiiben maradtak fenn, a várost ugyanis a Vezúv 79. évi kitörésekor láva és hamu lepte el, ami megőrizte a festményeket. Pompejiben fejlődött folyamatosan a falfestészet.  ", "Mozaikok az egykori Római Birodalom egész területén fennmaradtak. A mozaikok, mint az egész ókori művészet, elbeszélő jellegűek, történetet vagy eseményt ábrázolnak nagy természetességgel és realisztikusan. ", "A gliptika, a vésett faragású, illetve díszítésű, drágakövek vagy féldrágakövek művészete, szintén fejlett volt mind a helleniszikus, mind a római korban. ", "Egyiptom területének művészete a neolitikumba nyúlik vissza. A lakosság ekkor iszapból formált ovális vagy kerek alaprajzú kunyhókban lakott, halottaikat a kunyhók melletti ovális sírokba helyezték.  "
        , "Egyiptomban ez a kőrézkor (khalkolitikum) időszaka. A települések házait gazdagabban rendezték be, a sírokat olykor kővel rakták ki. Szövetmaradványok mutatják a szövés virágzását, feltűntek az első fajansztárgyak (kék és zöld színekben).  ", "A legátfogóbb képet a kerámiák tanulmányozása alapján lehet kapni. A változatos formájú, vörös, csiszolt csészék és tálak peremét gyakran feketével díszítették (főleg jellemző ez a Badári-kultúrára); máskor az edényfalon gazdag geometrikus ornamentika látható (Nagada I-II kultúrák). A minták között megjelent a figurális díszítés is (jelvény, hajó, ember, állatok). ", "A sírépületek a predinasztikus korból továbbfejlődtek, megnagyobbodtak. Bejáratuk Keletre nyílt, az ajtónál két sztélé állt. A kamrákat előbb kővel, majd téglával burkolták. Szakkarában és Abüdoszban a korszak uralkodóinak sírjai is fennmaradtak. ", "A másfél évszázados szétszakítottság után Egyiptom művészetét egyszerűség és realizmusra való törekvés jellemezte. Az építészet emlékei az egész ország területén fellelhetők, bár a későbbi idők rombolásai folytán csak kevés emlék maradt épen. Egy templom maradt fenn Fájjumban III. Amenemhat idejéből. Megvan oszlopcsarnoka, amely egy nagy kapun át előcsarnokba vezet, innen három kápolna nyílik.  "
        , "Piramisokat még építettek, de sokkal kisebb méretben és téglából, csak a belső kamrákat borították kővel. A piramisok körüli magánsírok téglából épültek. Közép- és Felső-Egyiptomban az előkelők oszlopos sírokat vájattak sziklába és falfestményekkel díszíttették. ", "A katakombák mennyezetfreskói geometrikus díszítésűek, a római és pompei festészet egyszerűsített változatai. A keresztény világképet jelképezik vörös és kék kontúrokkal. A madár-, és gyümölcsmotívumok szintén antik eredetűek. ", "Az antik templomokkal ellentétben, a keresztény templomokban a hangsúly a belső térre terelődik, hiszen a híveknek együtt kellett bemutatniuk az áldozatot s ez meghatározza a külalakot is. Az oszlopok a templom belsejében vannak, s nyugat-kelet irányban nagy mélység benyomását keltik.  ", "A képzőművészet fogalma mindazon művészeti ágakat felöleli, melyek eredményét nézni, látni lehet és célja nem valamely konkrét használati funkció kiszolgálása. A képzőművész szemléletének lényege, hogy gondolatai megfogalmazására autonóm műalkotás létrehozása céljával dolgozik. Nem fontos számára művének „használhatósága”. "
        };
        public string[] healthexcuse = { "Az orvostudomány célja az egészség fenntartása vagy éppen visszaállítása betegség vagy sérülés után. A test szerkezetével, működésével; a betegségek leírásával és az alkalmazott terápiákkal foglalkozik. Nem olyan absztrakt tudomány, mint a fizika vagy a kémia, hanem sok ezer éves tapasztalat, kísérlet és próbálkozás sűrített eredménye."
        , "Kínában már több ezer éve alkalmazták a himlőoltás egy korai formáját, amely azonban kockázatos volt és a beoltott személy kis eséllyel megkapta a feketehimlőt. 1717-ben Lady Mary Wortley Montagu Isztambulban tanúja volt a procedúrának és megpróbálta odahaza Angliában is elterjeszteni a módszert, de a társadalom ezt ellenállással fogadta. ", "A virus latin eredetű szó, jelentése méreg. Fertőző betegségekkel kapcsolatban először 1728-ban használták. ", "2014-ben 30 000 éves fagyott szibériai talajmintából izolálták az addig ismert legnagyobb vírust, a legkisebb eukarióta szervezetnél is nagyobb Pithovirust. ", "2005-ben az áldozatok megmaradt testszöveteiből sikerült rekonstruálni összeállítani az 1918-as spanyolnátha kórokozójának nukleinsav-szekvenciáját. A H1N1 típusú influenzavírust ezután megszintetizálták és laboratóriumban életképesnek bizonyult. 2009-ben egy másik H1N1 változat, az ún. sertésinfluenza okozott kisebb világjárványt. "
        , "Belső elválasztású mirigyek mindazon szervek, melyek sejtjei különböző hatást kifejtő hormonokat termelnek.  ", "Ingerületátvivő anyagokkal szabályozza a központi idegrendszer és a perifériás szervek között megvalósuló reflexkapcsolatokat. ", "Tevékenységét a belső elválasztású mirigyek által termelt hormonok segítségével fejti ki. ", "Az idegrendszerben keletkező kémiai anyagok –egyéb feladatuk mellett– hormonális hatást is kifejtenek. Különösen szoros kapcsolat van a központi idegrendszer egyik része, a hipotalamusz és az endokrin működés szabályozásában fontos szerepet betöltő agyalapi mirigy között. "
        , "A nemi mirigyek működéséért és a másodlagos nemi jelleg kialakulásáért, valamint az ivarsejtek termeléséért a megfelelő hormonok felelősek. ", "Az agyalapi mirigy több olyan hormont is termel, melyek felelősek más endokrin mirigy hormontermeléséért.  ", "Ugyan a klinikai gyakorlatban alkalmazott tesztek némelyike alkalmasak arra, hogy a páciens, célirányos kérdésekre adott válaszai írott formában dokumentálva legyenek, és támpontot jelenthetnek a depresszió és a szorongás súlyosságának mérésére, hátrányuk, hogy a válaszadás hitelességét biztosító válaszadói őszinteség – a kitöltéskor – nem ellenőrizhető, így e tesztek eredménye nem minősíthető objektív eredmények.  ", "A Beck-féle Depresszió Skála a depressziós állapot súlyosságának mérésére szolgál.  "
        , "Hippokratész több rákfajta leírását is elkészítette. A jóindulatú tumorokat onkosznak nevezte, ami duzzanatot jelent görögül, míg a rosszindulatú tumorokat karcinosznak hívta, ami a rák görög elnevezése.  ", "A szemhez vezető fejlődés első lépése a fényérzékelő sejtek megjelenése. A legkezdetlegesebb egysejtűek esetében a sejtmembrán bármely részén, elszórva jelentkeznek fényérzékeny foltok. A következő lépésben ezek egy meghatározott területre koncentrálódnak, szemfoltot alkotva. ", "A rabdomérák az elsődleges fényérzékelők, míg a csillós sejtek helye a gerincteleneknél az idegdúcban van. A gerinceseknél a csillós sejtekból alakultak ki a fényérzékelő felületet beborító csapok és pálcikák. ", "A modern kor egyik legfiatalabb és legnagyobb fejlődését mutató területe a kardiovaszkuláris sebészet, amely az 1940-es években indult fejlődésnek. "};
        public string[] sportexcuse = { "Nem is gondolnánk, hogy a sárkányrepülés is profi sportnak számít. Nos, Tahiföldön ez a sport is a profi sportok skáláját színesíti.", "Aki olvasta a Harry Potter könyveket, jól tudja, hogy mi is az a quidditch, vagy ahogyan magyarosan ejtjük: kviddics. Ez a játék, ma már nem csak egy elismert sport, hanem bajnokságot és világbajnokságot is rendeznek ebből a sportból. ", "A brazil fociválogatott tartja a csúcsot, már ami a sorozatos győzelmet illeti, ugyanis 1993 és 1996 között összesen 35 alkalommal sikerült győzedelmeskedniük. ", "Az amerikai profi kosárlabdajáték kiemelkedő alakja, Shaquille O’Neal, profi sportkarrierje során, mindössze egyetlen egyszer lőtt hárompontos gólt. "
        , "A kosárlabda átmérője pontosan a fele a kosárlabda gyűrű átmérőjének. ", "India 1900-ban csatlakozott az olimpiához, azaz vett részt az olimpiai játékokon és összesen 38 évet kellett várniuk, hogy az első olimpiai aranyérmet hazavigyék. ", "A jogging szót mindenki ismeri. Magyarul kocogást jelent. A jogging szó megalkotója, James Fixx volt. A sors fintora, hogy éppen kocogás közben, szívrohamban halt meg. ", "Miguel Indurain, a Tour de France ötszörös nyertese. Érdekesség ezzel kapcsolatban, hogy a nyugalmi pulzusa 28 ütés/perc. "
        , "A Nissan az autóversenyeken csakis a 23-as számot használja, mivel a második számot „ni”-nek, míg a harmadikat „san”-nak ejtik. Ebből a két szótagból pedig a „nissan” szó olvasható össze. ", "A világon az egyik legnépszerűbb sport a horgászat. Ezt a sportot űzik a legtöbben. Talán azért, mert ennél a sportnál nem kell mozogni? ", "A bokszot is sokan szeretik. Sokan űzik is ezt a sportot, és sokan járnak bokszversenyekre. Ez a sport 1901-ben vált legálissá. ", "A Mont Everestet már sokan próbálták meghódítani. Még néhány bátor nő is próbálta meghódítani a csúcsot. Az első nő, akinek sikerült is ezt az álmát megvalósítania nem más, mint a japán Junko Tubei, aki 1975-ben ért fel elsőként a Mont Everest csúcsára. "
        , "Sokan szeretnek tévét nézni és sokan imádják a sportközvetítéseket. Melyik sport vonzza a legjobban az embereket? Az emberek leginkább a következő sportközvetítéseket kedvelik: Forma-1, nyári olimpia és a labdarúgó-világbajnokság. ", "Újkori olimpiai játékokat legelőször Athénban rendeztek, mégpedig 1896-ban. A dolog érdekessége, hogy ezen az olimpián több mint háromszáz ember indult és egyetlen nő sem volt közöttük. ", "A teniszt sokan szeretik. Mit gondolsz, mi volt eddig a leghosszabb teniszmérkőzés? Nos, a leghosszabb meccs összesen 11 órán át tartott, mégpedig Wimbledonban. A mérkőzés John Isner és Nicolas Mahut között zajlott. ", "A labdás játékokhoz labdára van szükség. Azonban ezek a sporteszközök meghatározott kritériumok alapján készülnek. A futball-labda például 32 darabból áll, és 642 öltéssel készül, ezzel szemben a baseball-labdát csak 108 öltéssel készítik. "
        , "Forma1: Talán még a fiatalabb korosztályban is élénken él a kép, amikor a magyar érdekeltségű Hell energiaital a Williams szponzoraként jelen volt az F1-ben. Azonban nem ők voltak az elsők! Az 1991-es Magyar Nagydíjon Mika Hakkinen Lotusát egy hatalmas Magyar Hírlap logo díszítette, de ezzel is még csak másodikak ebben a sorban, ugyanis a legelső magyar Forma-1-es szponzor az 1987-es mogyoródi futamgyőztes Nelson Piquet autóján és sisakján jelent meg először. Ők voltak a Skála… ", "A legtöbb áldozatot követelő F1-es pálya: Niki Lauda ismert vesszőfutása okán sokan egyből rávágják, hogy ez a Nürburgring, de nem a német pálya vezet ebben a szomorú listában. A legtöbb halálos baleset egy olyan aszfaltcsíkhoz kötődik, amely már jó ideje nem szerepel a versenynaptárban. Ez az Indianapolis Motor Speedway, amely a versenyzés h(ős)korában, 1953 és 1959 között összesen nyolc áldozatot szedett. ", "A Forma-1 történelmének egyik legsikeresebb motorbeszállítója egy targoncagyár volt (!!). A Coventry Climax 1954 és 1965 között sikert sikerre halmozott. Furcsának tűnhet, hogy amíg a mai motor gyártók számos motorsportprogrammal és autógyártói tapasztalattal a hátuk mögött gyakran csak szenvednek, addig egy kizárólag targoncákat gyártó cég sikeres lehetett… ", "Forma1: Mike Hawthorn pilóta valószínűleg minden idők legfurcsább világbajnoka. A brit, aki amellett, hogy rendszerint csokornyakkendőben állt rajthoz, az 1958-as szezonban csupán egyetlen futamgyőzelemmel, és egyetlen pont előnnyel szerezte meg a végső győzelmet Stirling Moss előtt. "};
        public string[] codexcuse = { "Lelőttem volna ha be van pingelve.", "725 shotgun egy kifejezetten meta fegyver quadban", "Elég furcsán lőtt, tuti wh-zik. ", "Elég furcsán lőtt, tuti aimbotozik. ", "EZ IS CSAL, HÁT NEM HISZEM EL. "
        , "Én Battlefieldet szoktam meg azért nem megy a cod. ", "Én BF-ben tankokkal szoktam lenni ezért nem megy a COD. ", "Milyen jó lenne, ha lennének tankok a Battle Royaleban. ", "Onnan is lelő, hagyjuk már. "
        , "Az nem golyó, hanem lövedék. ", "Miért minket lő mindkettő csapat? ", "Ezek biztosan teamelnek. ", "Ebben a körben csak nem lesz csaló. "
        , "Loadout tiszta? Oké akkor odaugrok. AJAJ ITT VANNAK. ", "Akkor veszem is ki a PKM-et. ", "Valaki azt mondta hogy kell egy kali gamer? ", "Akkor én ide letámasztom a PKM-et. "
        , "Szerintem egyedül van fent. ...Hát nem gondoltam hogy mindenhol ülnek. "};

        //english
        public string[] codexcuseENG = { "English content under construction. Check back in 1 week." };
        public string[] lateENG = { "English content under construction. Check back in 1 week." };
        public string[] deadlineENG = { "English content under construction. Check back in 1 week." };
        public string[] trainingENG = { "English content under construction. Check back in 1 week." };
        public string[] sleepoverENG = { "English content under construction. Check back in 1 week." };
        public string[] businessENG = { "English content under construction. Check back in 1 week." };
        public string[] itENG = { "English content under construction. Check back in 1 week." };
    }
}